@startuml

entity "Пользователь (домовладелец)" as user {
  + id [PK]
  --
  ФИО : varchar(50)
  email : varchar(100) [UQ]
  дата_регистрации : date
}

entity Домовладение {
  + адрес [PK]
  --
  дата : datetime
  статус : enum('новый','в_процессе','подключён')
}

entity Устройство {
  + серийный_номер [PK]
  + тип_устройства_id [FK]  /* Внешний ключ */
  --
  дата_подключения : datetime
  статус : enum('работает','неисправно','отключено')
  
}

entity "Тип устройства" as DeviceType {
  + id [PK]
  --
  наименование : varchar(50)
  производитель : varchar(50)
}

entity "Тип  команды" as CommandType {
  + id [PK]
  + тип_устройства_id [FK]  /* Внешний ключ */
  --
  наименование : varchar(50)
  описание формата : JSON
}

entity "Тип значения датчика" as ValueType {
  + id [PK]
  + тип_устройства_id [FK]  /* Внешний ключ */
  --
  наименование : varchar(50)
  описание формата : JSON
}

entity "Реестр команд" as Command {
  + id [PK]
  + тип_команды_id [FK]  /* Внешний ключ */
  --
  команда : JSON
}

entity "Реестр значений датчиков" as Value {
  + id [PK]
  + тип_значения_id [FK]  /* Внешний ключ */
  --
  единица измерения : varchar(50)
  значение : JSON
}

Домовладение ||--o{ User : "принадлежит"
Устройство }--|| Домовладение : "расположено в"
Устройство }--|| DeviceType : "имеет тип"
CommandType }--|| DeviceType : " отностися к типу устройства"
ValueType }--|| DeviceType : " отностися к типу устройства"
Value }--|| ValueType : " тип"
Command }--|| DeviceType : " тип"

@enduml